### ISSUE TITLE
allow code blocks

### ISSUE THREAD

**Issue by MadcapJake** [shoichikaji/slack-perl6-evalbot#2]
You can write code blocks with an opening and closing set of backticks e.g., «```», and it would be awesome to have the slack code strip out the backticks before sending to get evaluated (you might have to strip any newline chars too).  This would make it possible to have multiline code blocks get executed which would be really cool!

**Comment by skaji** [comment]
Do you mean https://gist.github.com/skaji/545ded6704ab57403177 ?

Note:
Because you have to write `perl6` or `m` first to evaluate code, it is not so easy to write multiline code :-/

**Comment by MadcapJake** [comment]
That doesn't seem to work for me.  I tried just that gist and it fails with this error:

``````
===SORRY!=== Error while compiling /tmp/tempfile␤Bogus statement␤at /tmp/tempfile:1␤------> <BOL><HERE>```␤    expecting any of:␤        prefix␤        term␤
``````

**Comment by skaji** [comment]
Oh, I was just asking.

Try latest master branch. https://github.com/skaji/slack-perl6-evalbot/commit/d9a1193bbf436a78fb758c55b16e59009d8e490c

**Comment by MadcapJake** [comment]
Works great! Thanks so much!
