### ISSUE TITLE
multiple channels

### ISSUE THREAD

**Issue by MadcapJake** [shoichikaji/slack-perl6-evalbot#3]
Would it be possible to support multiple channels?  Currently the bot listens to other channels but prints the output only in the channel specified in the ENV var.  Would be great if the bot could be in all channels (and even better would be to allow support for private messages).

Also, I'd be willing to help wherever I can, though I didn't come to Perl 6 from Perl 5, so my Perl 5 skills are minimal.

**Comment by skaji** [comment]
> Would it be possible to support multiple channels?

Actually I don't know :-)
I'll check slack specification, and see what I can do.

**Comment by skaji** [comment]
Wow, multiple, private, direct channels have always been okay :laughing: 

Try latest master https://github.com/skaji/slack-perl6-evalbot/commit/5ee42d597d94147a99742c3957ee3e86442c0264

Then you don't have to specify SLACK_CHANNEL, and just invite camelia to your favorite channels.

**Comment by MadcapJake** [comment]
Thanks again for this!
